description: 'This component performs tests on the replica skeleton using ''skeleton_url''
  as input, ensuring it has been properly created and provides an overall status of
  the replica. Output({''replica_url'': str, ''replica_status'': str}).'
input-class: TestReplicaInputDict
name: TestReplica
output-class: TestReplicaOutputDict
parameters: {}
